#!/bin/bash
# Copyright (C) 2026 George Dobreff ("Witcher") and contributors
# SPDX-License-Identifier: GPL-3.0-only

build() {
    add_binary btrfs
    add_runscript
}

help() {
    cat <<HELPEOF
Factory reset for TarisOS: replaces the root with @factory, and the home folders with an empty
@home, when Settings asked for it.
HELPEOF
}
